#ifndef CA_CERT_H
#define CA_CERT_H

static const char ca_cert_pem[] =
"-----BEGIN CERTIFICATE-----\n"
"MIIBgDCCASegAwIBAgIUGsaWzNBNlQpcPpKry6LPYakLlv8wCgYIKoZIzj0EAwIw\n"
"FjEUMBIGA1UEAwwLbDBkZXN0YXIgQ0EwHhcNMjYwNjA5MTEyMTQ1WhcNMzYwNjA2\n"
"MTEyMTQ1WjAWMRQwEgYDVQQDDAtsMGRlc3RhciBDQTBZMBMGByqGSM49AgEGCCqG\n"
"SM49AwEHA0IABA9bATdkhlS1Gn+JJoft1abvuOe8CW1gZ87QFVVgWRMCkJrEiXJM\n"
"ZYaB/710ztOyOm42UfgbH5CX8g4TI6Gzn3SjUzBRMB0GA1UdDgQWBBSCAiz4n4ua\n"
"ovjLNHk1JxBXbcqtcDAfBgNVHSMEGDAWgBSCAiz4n4uaovjLNHk1JxBXbcqtcDAP\n"
"BgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIEsKbQCe64ZOxeTZFpsk\n"
"juP5RLWwdEl8tTDEJ2jVUq1CAiAoB/y0C4cK+9QAA1GBKQ1qi49aarUnrK0ajWjM\n"
"dVc1Dg==\n"
"-----END CERTIFICATE-----\n"
;

#endif
